#Mlops integration
wandb: 
  project: "mlops-star-type"
  entity: "geovanafreitas"

#Reproducibility and data.
data:
  raw_path: "dataset/raw/Stars.csv"
  test_size: 0.2 #20% of data for testing.
  random_state: 42 #Seed fixation for reproducibility.
  target_col: "Type" #Target variable.
  missing_threshold: 0.5 #Discard columns with more than 50% missing values.
  imputation_strategy: "mean" #Filling technique.

#MLP architecture.
model:
  hidden_sizes: [32, 16] #Two hidden layers: the first with 32 neurons and the second with 16.
  dropout: 0.2 #Random shutdown of 20% of neurons.
  learning_rate: 0.001 #How much the model weights change in response to the estimated error with each update.
  batch_size: 32 #Processing 32 samples at a time before updating their internal weights.
  epochs: 100 #Maximum limit of 100 complete passes through the dataset during training.
  early_stopping_patience: 10 #Discontinue training if the loss of validation does not improve for 10 consecutive seasons.