#Mlops integration.
wandb: 
  project: "mlops-star-type"
  entity: "geovanafreitas"

#Reproducibility and data.
data:
  raw_path: "dataset/raw/Stars.csv"
  test_size: 0.2
  random_state: 42
  target_col: "Type"
  missing_threshold: 0.5
  imputation_strategy: "mean"

#Feature Selection.
feature_selection:
  method: "combined"          #Pearson + mutual information + random forest.
  top_k: 7                    #Number of features to keep.
  use: true                   #Allows turning FS on/off easily.
  weights:
    pearson: 0.3
    mutual_info: 0.3
    random_forest: 0.4

#MLP architecture.
model:
  hidden_sizes: [32, 16]
  dropout: 0.2
  learning_rate: 0.001
  batch_size: 32
  epochs: 100
  early_stopping_patience: 10